
interface _GlobalComponents {
      'BaseBallFixturesMain': typeof import("../components/BaseBall/FixturesMain.vue")['default']
    'BaseBallLeagueMain': typeof import("../components/BaseBall/LeagueMain.vue")['default']
    'BaseBallLiveMain': typeof import("../components/BaseBall/LiveMain.vue")['default']
    'BaseBallOddsMain': typeof import("../components/BaseBall/OddsMain.vue")['default']
    'BaseBallResultMain': typeof import("../components/BaseBall/ResultMain.vue")['default']
    'BasketBallFixturesMain': typeof import("../components/BasketBall/FixturesMain.vue")['default']
    'BasketBallLeagueMain': typeof import("../components/BasketBall/LeagueMain.vue")['default']
    'BasketBallLiveMain': typeof import("../components/BasketBall/LiveMain.vue")['default']
    'BasketBallOddsMain': typeof import("../components/BasketBall/OddsMain.vue")['default']
    'BasketBallResultMain': typeof import("../components/BasketBall/ResultMain.vue")['default']
    'CommonFooterMain': typeof import("../components/Common/Footer/Main.vue")['default']
    'CommonHeaderMain': typeof import("../components/Common/Header/Main.vue")['default']
    'CommonHeaderTabLeague': typeof import("../components/Common/Header/TabLeague.vue")['default']
    'CommonHeaderTabMain': typeof import("../components/Common/Header/TabMain.vue")['default']
    'CommonHeaderTabMatchUp': typeof import("../components/Common/Header/TabMatchUp.vue")['default']
    'CommonLeftMain': typeof import("../components/Common/Left/Main.vue")['default']
    'FootBallFixturesMain': typeof import("../components/FootBall/FixturesMain.vue")['default']
    'FootBallLeagueMain': typeof import("../components/FootBall/LeagueMain.vue")['default']
    'FootBallLiveMain': typeof import("../components/FootBall/LiveMain.vue")['default']
    'FootBallOddsMain': typeof import("../components/FootBall/OddsMain.vue")['default']
    'FootBallResultMain': typeof import("../components/FootBall/ResultMain.vue")['default']
    'IceHockeyFixturesMain': typeof import("../components/IceHockey/FixturesMain.vue")['default']
    'IceHockeyLeagueMain': typeof import("../components/IceHockey/LeagueMain.vue")['default']
    'IceHockeyLiveMain': typeof import("../components/IceHockey/LiveMain.vue")['default']
    'IceHockeyOddsMain': typeof import("../components/IceHockey/OddsMain.vue")['default']
    'IceHockeyResultMain': typeof import("../components/IceHockey/ResultMain.vue")['default']
    'LeagueMatchUpMain': typeof import("../components/League/MatchUpMain.vue")['default']
    'LeagueOddsMain': typeof import("../components/League/OddsMain.vue")['default']
    'LeaguePlayersMain': typeof import("../components/League/PlayersMain.vue")['default']
    'LeagueResultMain': typeof import("../components/League/ResultMain.vue")['default']
    'LeagueTableMain': typeof import("../components/League/TableMain.vue")['default']
    'LoadingSpinner': typeof import("../components/Loading/Spinner.vue")['default']
    'MatchUpH2hMain': typeof import("../components/MatchUp/H2hMain.vue")['default']
    'MatchUpLineUpMain': typeof import("../components/MatchUp/LineUpMain.vue")['default']
    'MatchUpNavitalkMain': typeof import("../components/MatchUp/NavitalkMain.vue")['default']
    'MatchUpOddsMain': typeof import("../components/MatchUp/OddsMain.vue")['default']
    'MatchUpStatsMain': typeof import("../components/MatchUp/StatsMain.vue")['default']
    'TennisFixturesMain': typeof import("../components/Tennis/FixturesMain.vue")['default']
    'TennisLeagueMain': typeof import("../components/Tennis/LeagueMain.vue")['default']
    'TennisLiveMain': typeof import("../components/Tennis/LiveMain.vue")['default']
    'TennisOddsMain': typeof import("../components/Tennis/OddsMain.vue")['default']
    'TennisResultMain': typeof import("../components/Tennis/ResultMain.vue")['default']
    'VolleyBallFixturesMain': typeof import("../components/VolleyBall/FixturesMain.vue")['default']
    'VolleyBallLeagueMain': typeof import("../components/VolleyBall/LeagueMain.vue")['default']
    'VolleyBallLiveMain': typeof import("../components/VolleyBall/LiveMain.vue")['default']
    'VolleyBallOddsMain': typeof import("../components/VolleyBall/OddsMain.vue")['default']
    'VolleyBallResultMain': typeof import("../components/VolleyBall/ResultMain.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyBaseBallFixturesMain': typeof import("../components/BaseBall/FixturesMain.vue")['default']
    'LazyBaseBallLeagueMain': typeof import("../components/BaseBall/LeagueMain.vue")['default']
    'LazyBaseBallLiveMain': typeof import("../components/BaseBall/LiveMain.vue")['default']
    'LazyBaseBallOddsMain': typeof import("../components/BaseBall/OddsMain.vue")['default']
    'LazyBaseBallResultMain': typeof import("../components/BaseBall/ResultMain.vue")['default']
    'LazyBasketBallFixturesMain': typeof import("../components/BasketBall/FixturesMain.vue")['default']
    'LazyBasketBallLeagueMain': typeof import("../components/BasketBall/LeagueMain.vue")['default']
    'LazyBasketBallLiveMain': typeof import("../components/BasketBall/LiveMain.vue")['default']
    'LazyBasketBallOddsMain': typeof import("../components/BasketBall/OddsMain.vue")['default']
    'LazyBasketBallResultMain': typeof import("../components/BasketBall/ResultMain.vue")['default']
    'LazyCommonFooterMain': typeof import("../components/Common/Footer/Main.vue")['default']
    'LazyCommonHeaderMain': typeof import("../components/Common/Header/Main.vue")['default']
    'LazyCommonHeaderTabLeague': typeof import("../components/Common/Header/TabLeague.vue")['default']
    'LazyCommonHeaderTabMain': typeof import("../components/Common/Header/TabMain.vue")['default']
    'LazyCommonHeaderTabMatchUp': typeof import("../components/Common/Header/TabMatchUp.vue")['default']
    'LazyCommonLeftMain': typeof import("../components/Common/Left/Main.vue")['default']
    'LazyFootBallFixturesMain': typeof import("../components/FootBall/FixturesMain.vue")['default']
    'LazyFootBallLeagueMain': typeof import("../components/FootBall/LeagueMain.vue")['default']
    'LazyFootBallLiveMain': typeof import("../components/FootBall/LiveMain.vue")['default']
    'LazyFootBallOddsMain': typeof import("../components/FootBall/OddsMain.vue")['default']
    'LazyFootBallResultMain': typeof import("../components/FootBall/ResultMain.vue")['default']
    'LazyIceHockeyFixturesMain': typeof import("../components/IceHockey/FixturesMain.vue")['default']
    'LazyIceHockeyLeagueMain': typeof import("../components/IceHockey/LeagueMain.vue")['default']
    'LazyIceHockeyLiveMain': typeof import("../components/IceHockey/LiveMain.vue")['default']
    'LazyIceHockeyOddsMain': typeof import("../components/IceHockey/OddsMain.vue")['default']
    'LazyIceHockeyResultMain': typeof import("../components/IceHockey/ResultMain.vue")['default']
    'LazyLeagueMatchUpMain': typeof import("../components/League/MatchUpMain.vue")['default']
    'LazyLeagueOddsMain': typeof import("../components/League/OddsMain.vue")['default']
    'LazyLeaguePlayersMain': typeof import("../components/League/PlayersMain.vue")['default']
    'LazyLeagueResultMain': typeof import("../components/League/ResultMain.vue")['default']
    'LazyLeagueTableMain': typeof import("../components/League/TableMain.vue")['default']
    'LazyLoadingSpinner': typeof import("../components/Loading/Spinner.vue")['default']
    'LazyMatchUpH2hMain': typeof import("../components/MatchUp/H2hMain.vue")['default']
    'LazyMatchUpLineUpMain': typeof import("../components/MatchUp/LineUpMain.vue")['default']
    'LazyMatchUpNavitalkMain': typeof import("../components/MatchUp/NavitalkMain.vue")['default']
    'LazyMatchUpOddsMain': typeof import("../components/MatchUp/OddsMain.vue")['default']
    'LazyMatchUpStatsMain': typeof import("../components/MatchUp/StatsMain.vue")['default']
    'LazyTennisFixturesMain': typeof import("../components/Tennis/FixturesMain.vue")['default']
    'LazyTennisLeagueMain': typeof import("../components/Tennis/LeagueMain.vue")['default']
    'LazyTennisLiveMain': typeof import("../components/Tennis/LiveMain.vue")['default']
    'LazyTennisOddsMain': typeof import("../components/Tennis/OddsMain.vue")['default']
    'LazyTennisResultMain': typeof import("../components/Tennis/ResultMain.vue")['default']
    'LazyVolleyBallFixturesMain': typeof import("../components/VolleyBall/FixturesMain.vue")['default']
    'LazyVolleyBallLeagueMain': typeof import("../components/VolleyBall/LeagueMain.vue")['default']
    'LazyVolleyBallLiveMain': typeof import("../components/VolleyBall/LiveMain.vue")['default']
    'LazyVolleyBallOddsMain': typeof import("../components/VolleyBall/OddsMain.vue")['default']
    'LazyVolleyBallResultMain': typeof import("../components/VolleyBall/ResultMain.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BaseBallFixturesMain: typeof import("../components/BaseBall/FixturesMain.vue")['default']
export const BaseBallLeagueMain: typeof import("../components/BaseBall/LeagueMain.vue")['default']
export const BaseBallLiveMain: typeof import("../components/BaseBall/LiveMain.vue")['default']
export const BaseBallOddsMain: typeof import("../components/BaseBall/OddsMain.vue")['default']
export const BaseBallResultMain: typeof import("../components/BaseBall/ResultMain.vue")['default']
export const BasketBallFixturesMain: typeof import("../components/BasketBall/FixturesMain.vue")['default']
export const BasketBallLeagueMain: typeof import("../components/BasketBall/LeagueMain.vue")['default']
export const BasketBallLiveMain: typeof import("../components/BasketBall/LiveMain.vue")['default']
export const BasketBallOddsMain: typeof import("../components/BasketBall/OddsMain.vue")['default']
export const BasketBallResultMain: typeof import("../components/BasketBall/ResultMain.vue")['default']
export const CommonFooterMain: typeof import("../components/Common/Footer/Main.vue")['default']
export const CommonHeaderMain: typeof import("../components/Common/Header/Main.vue")['default']
export const CommonHeaderTabLeague: typeof import("../components/Common/Header/TabLeague.vue")['default']
export const CommonHeaderTabMain: typeof import("../components/Common/Header/TabMain.vue")['default']
export const CommonHeaderTabMatchUp: typeof import("../components/Common/Header/TabMatchUp.vue")['default']
export const CommonLeftMain: typeof import("../components/Common/Left/Main.vue")['default']
export const FootBallFixturesMain: typeof import("../components/FootBall/FixturesMain.vue")['default']
export const FootBallLeagueMain: typeof import("../components/FootBall/LeagueMain.vue")['default']
export const FootBallLiveMain: typeof import("../components/FootBall/LiveMain.vue")['default']
export const FootBallOddsMain: typeof import("../components/FootBall/OddsMain.vue")['default']
export const FootBallResultMain: typeof import("../components/FootBall/ResultMain.vue")['default']
export const IceHockeyFixturesMain: typeof import("../components/IceHockey/FixturesMain.vue")['default']
export const IceHockeyLeagueMain: typeof import("../components/IceHockey/LeagueMain.vue")['default']
export const IceHockeyLiveMain: typeof import("../components/IceHockey/LiveMain.vue")['default']
export const IceHockeyOddsMain: typeof import("../components/IceHockey/OddsMain.vue")['default']
export const IceHockeyResultMain: typeof import("../components/IceHockey/ResultMain.vue")['default']
export const LeagueMatchUpMain: typeof import("../components/League/MatchUpMain.vue")['default']
export const LeagueOddsMain: typeof import("../components/League/OddsMain.vue")['default']
export const LeaguePlayersMain: typeof import("../components/League/PlayersMain.vue")['default']
export const LeagueResultMain: typeof import("../components/League/ResultMain.vue")['default']
export const LeagueTableMain: typeof import("../components/League/TableMain.vue")['default']
export const LoadingSpinner: typeof import("../components/Loading/Spinner.vue")['default']
export const MatchUpH2hMain: typeof import("../components/MatchUp/H2hMain.vue")['default']
export const MatchUpLineUpMain: typeof import("../components/MatchUp/LineUpMain.vue")['default']
export const MatchUpNavitalkMain: typeof import("../components/MatchUp/NavitalkMain.vue")['default']
export const MatchUpOddsMain: typeof import("../components/MatchUp/OddsMain.vue")['default']
export const MatchUpStatsMain: typeof import("../components/MatchUp/StatsMain.vue")['default']
export const TennisFixturesMain: typeof import("../components/Tennis/FixturesMain.vue")['default']
export const TennisLeagueMain: typeof import("../components/Tennis/LeagueMain.vue")['default']
export const TennisLiveMain: typeof import("../components/Tennis/LiveMain.vue")['default']
export const TennisOddsMain: typeof import("../components/Tennis/OddsMain.vue")['default']
export const TennisResultMain: typeof import("../components/Tennis/ResultMain.vue")['default']
export const VolleyBallFixturesMain: typeof import("../components/VolleyBall/FixturesMain.vue")['default']
export const VolleyBallLeagueMain: typeof import("../components/VolleyBall/LeagueMain.vue")['default']
export const VolleyBallLiveMain: typeof import("../components/VolleyBall/LiveMain.vue")['default']
export const VolleyBallOddsMain: typeof import("../components/VolleyBall/OddsMain.vue")['default']
export const VolleyBallResultMain: typeof import("../components/VolleyBall/ResultMain.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyBaseBallFixturesMain: typeof import("../components/BaseBall/FixturesMain.vue")['default']
export const LazyBaseBallLeagueMain: typeof import("../components/BaseBall/LeagueMain.vue")['default']
export const LazyBaseBallLiveMain: typeof import("../components/BaseBall/LiveMain.vue")['default']
export const LazyBaseBallOddsMain: typeof import("../components/BaseBall/OddsMain.vue")['default']
export const LazyBaseBallResultMain: typeof import("../components/BaseBall/ResultMain.vue")['default']
export const LazyBasketBallFixturesMain: typeof import("../components/BasketBall/FixturesMain.vue")['default']
export const LazyBasketBallLeagueMain: typeof import("../components/BasketBall/LeagueMain.vue")['default']
export const LazyBasketBallLiveMain: typeof import("../components/BasketBall/LiveMain.vue")['default']
export const LazyBasketBallOddsMain: typeof import("../components/BasketBall/OddsMain.vue")['default']
export const LazyBasketBallResultMain: typeof import("../components/BasketBall/ResultMain.vue")['default']
export const LazyCommonFooterMain: typeof import("../components/Common/Footer/Main.vue")['default']
export const LazyCommonHeaderMain: typeof import("../components/Common/Header/Main.vue")['default']
export const LazyCommonHeaderTabLeague: typeof import("../components/Common/Header/TabLeague.vue")['default']
export const LazyCommonHeaderTabMain: typeof import("../components/Common/Header/TabMain.vue")['default']
export const LazyCommonHeaderTabMatchUp: typeof import("../components/Common/Header/TabMatchUp.vue")['default']
export const LazyCommonLeftMain: typeof import("../components/Common/Left/Main.vue")['default']
export const LazyFootBallFixturesMain: typeof import("../components/FootBall/FixturesMain.vue")['default']
export const LazyFootBallLeagueMain: typeof import("../components/FootBall/LeagueMain.vue")['default']
export const LazyFootBallLiveMain: typeof import("../components/FootBall/LiveMain.vue")['default']
export const LazyFootBallOddsMain: typeof import("../components/FootBall/OddsMain.vue")['default']
export const LazyFootBallResultMain: typeof import("../components/FootBall/ResultMain.vue")['default']
export const LazyIceHockeyFixturesMain: typeof import("../components/IceHockey/FixturesMain.vue")['default']
export const LazyIceHockeyLeagueMain: typeof import("../components/IceHockey/LeagueMain.vue")['default']
export const LazyIceHockeyLiveMain: typeof import("../components/IceHockey/LiveMain.vue")['default']
export const LazyIceHockeyOddsMain: typeof import("../components/IceHockey/OddsMain.vue")['default']
export const LazyIceHockeyResultMain: typeof import("../components/IceHockey/ResultMain.vue")['default']
export const LazyLeagueMatchUpMain: typeof import("../components/League/MatchUpMain.vue")['default']
export const LazyLeagueOddsMain: typeof import("../components/League/OddsMain.vue")['default']
export const LazyLeaguePlayersMain: typeof import("../components/League/PlayersMain.vue")['default']
export const LazyLeagueResultMain: typeof import("../components/League/ResultMain.vue")['default']
export const LazyLeagueTableMain: typeof import("../components/League/TableMain.vue")['default']
export const LazyLoadingSpinner: typeof import("../components/Loading/Spinner.vue")['default']
export const LazyMatchUpH2hMain: typeof import("../components/MatchUp/H2hMain.vue")['default']
export const LazyMatchUpLineUpMain: typeof import("../components/MatchUp/LineUpMain.vue")['default']
export const LazyMatchUpNavitalkMain: typeof import("../components/MatchUp/NavitalkMain.vue")['default']
export const LazyMatchUpOddsMain: typeof import("../components/MatchUp/OddsMain.vue")['default']
export const LazyMatchUpStatsMain: typeof import("../components/MatchUp/StatsMain.vue")['default']
export const LazyTennisFixturesMain: typeof import("../components/Tennis/FixturesMain.vue")['default']
export const LazyTennisLeagueMain: typeof import("../components/Tennis/LeagueMain.vue")['default']
export const LazyTennisLiveMain: typeof import("../components/Tennis/LiveMain.vue")['default']
export const LazyTennisOddsMain: typeof import("../components/Tennis/OddsMain.vue")['default']
export const LazyTennisResultMain: typeof import("../components/Tennis/ResultMain.vue")['default']
export const LazyVolleyBallFixturesMain: typeof import("../components/VolleyBall/FixturesMain.vue")['default']
export const LazyVolleyBallLeagueMain: typeof import("../components/VolleyBall/LeagueMain.vue")['default']
export const LazyVolleyBallLiveMain: typeof import("../components/VolleyBall/LiveMain.vue")['default']
export const LazyVolleyBallOddsMain: typeof import("../components/VolleyBall/OddsMain.vue")['default']
export const LazyVolleyBallResultMain: typeof import("../components/VolleyBall/ResultMain.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
